import random
psight = int(input("..."))
a = random.randint(1, 24)
b2 = (random.randint(-20, -1))
b = (10^b2)
c = (random.choice([-1, 1]))
d = (1 - c * b)
nsight = psight * a * d
print(psight)
print(a)
print(b2)
print(b)
print(c)
print(d)
print(nsight)